# docker compose for fastapi

version: '3'
services:
  web:
    build: .
    container_name: "fastapi_test2"
    ports:
      - "8000:8000"
    command: uvicorn daily_data:app --host=0.0.0.0 --port=8000
